version: "3.8"

services:

# PROXY
  traefik:
    image: "traefik:v3.0"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - network_tools

# MAILBOX
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - network_tools

  whoami:
    image: "containous/whoami"
    container_name: "whoami"
    command:
      - "--port=32000"
    labels:
      - "traefik.enable=true"
    networks:
      - network_tools

networks:
  network_tools:
    name: "network_app"